name: zoomable_image_example
description: Demonstrates how to use the zoomable_image plugin.

dependencies:
  flutter:
    sdk: flutter
  image_tap_coordinates:
    path: ../

flutter:
  assets:
   - images/squirrel.jpg
